apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doctor-booking

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgresql.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app: doctor-booking
  env: base

# Add name prefix for all resources
namePrefix: ""

# Add name suffix for all resources
nameSuffix: ""

# Add common annotations to all resources
commonAnnotations:
  managed-by: kustomize
  version: v1.0.0
