apiVersion: v1
kind: Secret
metadata:
  name: doctor-booking-secrets
  namespace: doctor-booking
type: Opaque
data:
  # echo -n 'your_secure_password' | base64
  DB_PASSWORD: cG9zdGdyZXM=  # Default is 'postgres', change this in production
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl  # Default is 'your_jwt_secret_key_here', change this in production
