version: '3.8'

services:
  # Production build
  app:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - frontend-network

  # Development environment with hot-reloading
  dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    command: sh -c "npm install && npm run dev"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
